development:
  adapter: postgresql
  encoding: unicode
  database: gradejoy_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: gradejoy_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: gradejoy_production
  pool: 5
